version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_serenity
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: serenity_root
      MYSQL_DATABASE: serenity
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
